import { app, BrowserWindow, dialog, ipcMain, shell } from 'electron';
import { spawn, execFileSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import fs from 'node:fs/promises';
import fsSync from 'node:fs';
import os from 'node:os';

const APP_ID='com.robloxforge.desktop';const DESKTOP_DIR=path.dirname(fileURLToPath(import.meta.url));const APP_ROOT=path.dirname(DESKTOP_DIR);const CONFIG_FILE=()=>path.join(app.getPath('userData'),'forge-config.json');const MEMORY_FILE=()=>path.join(app.getPath('userData'),'forge-workspace.json');const children=new Map();let projectRoot=null;let mainWindow=null;let externalAgents=false;app.setAppUserModelId(APP_ID);
const exists=async p=>{try{await fs.access(p);return true}catch{return false}};const requirePath=async(r,...p)=>exists(path.join(r,...p));
async function isValidProject(r){return Boolean(r)&&await requirePath(r,'default.project.json')&&await requirePath(r,'src')&&await requirePath(r,'tools','roblox-forge','forge-server.mjs')}
async function findProjectInside(root,maxDepth=4){if(!root||maxDepth<0)return null;if(await isValidProject(root))return path.normalize(root);if(!maxDepth)return null;let es;try{es=await fs.readdir(root,{withFileTypes:true})}catch{return null}const ds=es.filter(e=>e.isDirectory()&&!e.name.startsWith('.')&&!['node_modules','dist'].includes(e.name)).sort((a,b)=>(a.name.toLowerCase()==='worldshift'?0:1)-(b.name.toLowerCase()==='worldshift'?0:1)||a.name.localeCompare(b.name));for(const e of ds){const f=await findProjectInside(path.join(root,e.name),maxDepth-1);if(f)return f}return null}
async function findProject(){const h=os.homedir(),od=process.env.OneDrive||process.env.OneDriveConsumer;for(const c of [...new Set([path.join(h,'Desktop'),path.join(h,'OneDrive','Desktop'),od&&path.join(od,'Desktop'),path.join(h,'Documents'),path.join(h,'OneDrive','Documents'),od&&path.join(od,'Documents'),process.cwd()].filter(Boolean).map(path.normalize))]){const f=await findProjectInside(c);if(f)return f}return null}
async function loadConfig(){try{const c=JSON.parse(await fs.readFile(CONFIG_FILE(),'utf8'));projectRoot=await findProjectInside(c.projectRoot,2)}catch{}if(!projectRoot)projectRoot=await findProject();if(projectRoot)await saveConfig()}async function saveConfig(){await fs.mkdir(app.getPath('userData'),{recursive:true});await fs.writeFile(CONFIG_FILE(),JSON.stringify({projectRoot},null,2),'utf8')}
async function loadWorkspace(){try{return JSON.parse(await fs.readFile(MEMORY_FILE(),'utf8'))}catch{return{memory:'',tasks:[],decisions:[],updatedAt:null}}}async function saveWorkspace(d){d.updatedAt=new Date().toISOString();await fs.mkdir(app.getPath('userData'),{recursive:true});await fs.writeFile(MEMORY_FILE(),JSON.stringify(d,null,2),'utf8');return d}
const forgePath=()=>path.join(projectRoot,'tools','roblox-forge','forge-server.mjs');const rojoPath=()=>path.join(projectRoot,'default.project.json');const agentsPath=()=>path.join(projectRoot,'tools','roblox-forge','agents','orchestrator.mjs');const bundledAgentsPath=()=>path.join(APP_ROOT,'agents','orchestrator.mjs');const bundledRegistryPath=()=>path.join(APP_ROOT,'agents','registry.json');const pluginSource=()=>path.join(projectRoot,'tools','roblox-forge','studio','ForgePlugin.server.lua');const pluginTarget=()=>path.join(process.env.LOCALAPPDATA||path.join(os.homedir(),'AppData','Local'),'Roblox','Plugins','RobloxForge.lua');
function findOnPath(c){if(process.platform!=='win32')return null;try{return execFileSync('where.exe',[c],{encoding:'utf8',windowsHide:true,stdio:['ignore','pipe','ignore']}).split(/\r?\n/).map(x=>x.trim()).find(Boolean)||null}catch{return null}}function isFile(p){try{return fsSync.existsSync(p)&&fsSync.statSync(p).isFile()}catch{return false}}function resolveRojo(){const e=process.env.ROJO_PATH?.trim();if(e&&isFile(e))return path.normalize(e);const f=findOnPath('rojo');if(f)return f;const h=os.homedir(),l=process.env.LOCALAPPDATA||path.join(h,'AppData','Local'),r=process.env.APPDATA||path.join(h,'AppData','Roaming');return[path.join('C:','Rojo','rojo.exe'),path.join('C:','Rojo','bin','rojo.exe'),path.join('C:','Program Files','Rojo','rojo.exe'),path.join(h,'.cargo','bin','rojo.exe'),path.join(h,'.aftman','bin','rojo.exe'),path.join(h,'.foreman','bin','rojo.exe'),path.join(r,'Aftman','bin','rojo.exe'),path.join(h,'scoop','shims','rojo.exe'),path.join(l,'Rojo','rojo.exe'),path.join(l,'Programs','Rojo','rojo.exe'),path.join(l,'Programs','Aftman','bin','rojo.exe'),...(projectRoot?[path.join(projectRoot,'.aftman','bin','rojo.exe'),path.join(projectRoot,'.foreman','bin','rojo.exe')]:[])].find(isFile)||null}
function resolveNode(){const e=process.env.FORGE_NODE?.trim();if(e&&isFile(e))return e;return findOnPath('node')||'node'}
function definitions(){if(!projectRoot)return{};return{forge:{label:'Forge Bridge',command:resolveNode(),args:[forgePath()]},rojo:{label:'Rojo',command:resolveRojo()||'rojo',args:['serve',rojoPath()]},agents:{label:'AI Orchestrator',command:resolveNode(),args:[isFile(agentsPath())?agentsPath():bundledAgentsPath()]}}}
const send=(c,p)=>{if(mainWindow&&!mainWindow.isDestroyed())mainWindow.webContents.send(c,p)};
async function httpJson(url,options={}){const r=await fetch(url,options);const text=await r.text();let d;try{d=text?JSON.parse(text):{}}catch{d={raw:text}}if(!r.ok)throw Error(d.error||`HTTP ${r.status}`);return d}
async function waitFor(url,timeout=8000,interval=250){const end=Date.now()+timeout;let last='';while(Date.now()<end){try{return await httpJson(url)}catch(e){last=e.message;await new Promise(r=>setTimeout(r,interval))}}throw Error(last||`Timeout waiting for ${url}`)}
async function agentPortAlive(){try{await httpJson('http://127.0.0.1:43118/health');return true}catch{return false}}
function start(id){if(!projectRoot)throw Error('Nejdřív vyber projekt WORLDSHIFT.');if(children.has(id))return{ok:true,running:true,alreadyRunning:true,pid:children.get(id).entry.pid};if(id==='agents'&&externalAgents)return{ok:true,running:true,external:true,pid:null};const d=definitions()[id];if(!d)throw Error(`Neznámý proces: ${id}`);if(id==='rojo'&&!resolveRojo())throw Error('Rojo nebyl nalezen. Nainstaluj Rojo nebo nastav ROJO_PATH.');if(id==='agents'&&!isFile(agentsPath())&&!isFile(bundledAgentsPath()))throw Error(`AI Orchestrator nebyl nalezen ani v projektu, ani v instalaci Forge.`);const env={...process.env,FORCE_COLOR:'0'};if(id==='agents'){env.FORGE_PROJECT_ROOT=projectRoot;env.FORGE_REGISTRY_PATH=isFile(agentsPath())?path.join(projectRoot,'tools','roblox-forge','agents','registry.json'):bundledRegistryPath();env.FORGE_FORGE_ROOT=APP_ROOT}const child=spawn(d.command,d.args,{cwd:projectRoot,env,windowsHide:true,shell:false,stdio:['pipe','pipe','pipe']});const entry={id,label:d.label,pid:child.pid??null,running:true,log:''};children.set(id,{child,entry});const append=x=>{entry.log=(entry.log+String(x)).slice(-50000);send('process-log',{id,text:String(x)})};child.stdout?.on('data',append);child.stderr?.on('data',append);child.on('error',e=>{append(`[FORGE ERROR] ${e.message}\n`);entry.running=false;children.delete(id);send('process-exit',{id,code:null,signal:null,error:e.message})});child.on('exit',(code,signal)=>{entry.running=false;entry.exitCode=code;entry.signal=signal;children.delete(id);send('process-exit',{id,code,signal})});append(`[FORGE] Starting ${d.label} (PID ${child.pid??'unknown'})\n`);return{ok:true,running:true,pid:child.pid??null}}
function stop(id){if(id==='agents'&&externalAgents)return{ok:true,running:true,external:true,alreadyExternal:true};const x=children.get(id);if(!x)return{ok:true,running:false,alreadyStopped:true};try{x.child.kill()}catch{}children.delete(id);return{ok:true,running:false}}function stopAll(){for(const id of [...children.keys()])stop(id);externalAgents=false}function status(){return Object.entries(definitions()).map(([id,d])=>{const x=children.get(id);return{id,label:d.label,running:Boolean(x)||(id==='agents'&&externalAgents),pid:x?.entry.pid??null,log:x?.entry.log??(externalAgents?'AI Orchestrator is already running on port 43118.':'')}})}
async function chooseProject(){const r=await dialog.showOpenDialog(mainWindow,{title:'Vyber složku projektu WORLDSHIFT',defaultPath:projectRoot||path.join(os.homedir(),'Desktop'),buttonLabel:'PŘIPOJIT PROJEKT',properties:['openDirectory']});if(r.canceled||!r.filePaths?.[0])return{ok:false,canceled:true,projectRoot};const f=await findProjectInside(path.normalize(r.filePaths[0]),5);if(!f){await dialog.showMessageBox(mainWindow,{type:'error',title:'ROBLOX FORGE — projekt nenalezen',message:'V této složce nebyl nalezen platný WORLDSHIFT projekt.',detail:'Vyber složku s default.project.json.'});return{ok:false,invalid:true,projectRoot}}stopAll();projectRoot=f;await saveConfig();return{ok:true,projectRoot}}
async function resetProject(){stopAll();projectRoot=null;try{await fs.rm(CONFIG_FILE(),{force:true})}catch{}return{ok:true,projectRoot:null}}async function installStudioPlugin(){if(!projectRoot)throw Error('Nejdřív vyber projekt WORLDSHIFT.');if(!await exists(pluginSource()))throw Error(`Studio plugin nebyl nalezen: ${pluginSource()}`);const t=pluginTarget();await fs.mkdir(path.dirname(t),{recursive:true});await fs.copyFile(pluginSource(),t);return{ok:true,target:t}}
async function forgeGet(p){return httpJson(`http://127.0.0.1:43117${p}`)}async function studioHealth(){try{const d=await forgeGet('/api/studio/state');return{online:true,connected:Boolean(d.connected),heartbeat:d.heartbeat||null,studio:d.studio||null}}catch(e){return{online:false,connected:false,reason:e.message}}}
async function agentGet(p){return httpJson(`http://127.0.0.1:43118${p}`)}async function agentPost(p,b){return httpJson(`http://127.0.0.1:43118${p}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)})}async function ensureAgents(){if(await agentPortAlive()){externalAgents=!children.has('agents');return await agentGet('/agents')}externalAgents=false;if(!children.has('agents'))start('agents');const health=await waitFor('http://127.0.0.1:43118/health',10000);if(!health.ok)throw Error('AI Orchestrator nenahlásil zdraví.');return agentGet('/agents')}
async function createWindow(){mainWindow=new BrowserWindow({width:1400,height:900,minWidth:1100,minHeight:720,title:'ROBLOX FORGE',backgroundColor:'#070a10',show:false,webPreferences:{preload:path.join(DESKTOP_DIR,'preload.cjs'),contextIsolation:true,nodeIntegration:false,sandbox:true}});mainWindow.loadFile(path.join(DESKTOP_DIR,'index.html'));mainWindow.webContents.on('preload-error',(_e,p,e)=>send('app-error',{message:`Preload error: ${p}: ${e.message}`}));mainWindow.webContents.on('render-process-gone',(_e,d)=>send('app-error',{message:`Renderer ukončen: ${d.reason}`}));mainWindow.once('ready-to-show',()=>mainWindow.show())}
ipcMain.handle('app-info',()=>({version:app.getVersion(),packaged:app.isPackaged,platform:process.platform}));ipcMain.handle('project-get',()=>({projectRoot}));ipcMain.handle('project-choose',chooseProject);ipcMain.handle('project-reset',resetProject);ipcMain.handle('studio-install',installStudioPlugin);ipcMain.handle('studio-health',studioHealth);ipcMain.handle('process-status',()=>status());ipcMain.handle('process-start',(_e,id)=>start(id));ipcMain.handle('process-stop',(_e,id)=>stop(id));ipcMain.handle('stack-start',async()=>{if(!projectRoot)throw Error('Nejdřív vyber projekt WORLDSHIFT.');const results={};results.plugin=await installStudioPlugin();try{if(!children.has('forge'))start('forge');results.forge=await waitFor('http://127.0.0.1:43117/api/health',10000)}catch(e){results.forge={ok:false,error:e.message}}try{results.rojo=start('rojo')}catch(e){results.rojo={ok:false,error:e.message}}try{results.agents=await ensureAgents()}catch(e){results.agents={ok:false,error:e.message}}return{ok:Boolean(results.forge?.ok&&results.agents?.ok),results,processes:status()}});ipcMain.handle('stack-stop',()=>{stopAll();return{ok:true,processes:status()}});ipcMain.handle('process-input',(_e,id,input)=>{const x=children.get(id);if(!x?.child.stdin?.writable)throw Error(`${id} neběží.`);x.child.stdin.write(String(input));return{ok:true}});ipcMain.handle('open-folder',()=>projectRoot?shell.openPath(projectRoot):chooseProject());ipcMain.handle('workspace-get',loadWorkspace);ipcMain.handle('workspace-save',(_e,d)=>saveWorkspace(d));ipcMain.handle('diagnostics',async()=>{try{return await forgeGet('/api/diagnostics')}catch(e){return{ok:false,error:e.message}}});ipcMain.handle('studio-state',async()=>{try{return await forgeGet('/api/studio/state')}catch(e){return{ok:false,error:e.message}}});ipcMain.handle('agents-list',async()=>{try{return await ensureAgents()}catch(e){return{ok:false,error:e.message,agents:[]}}});ipcMain.handle('agent-run',async(_e,p)=>{if(!p?.prompt)throw Error('Zadej úkol pro AI.');await ensureAgents();return agentPost('/run',{role:p.role||'coder',prompt:p.prompt,agentId:p.agentId||undefined,policy:'supervised'})});ipcMain.handle('agent-stop',(_e,id)=>agentPost('/stop',{id}));
process.on('uncaughtException',e=>send('app-error',{message:e.message,stack:e.stack}));process.on('unhandledRejection',r=>send('app-error',{message:String(r)}));app.whenReady().then(async()=>{await loadConfig();createWindow()});app.on('before-quit',stopAll);app.on('window-all-closed',()=>{if(process.platform!=='darwin')app.quit()});